# Example configuration using publicly available test APIs
# This can be used for testing without requiring actual production APIs

global:
  name: "enhanced-flex-monitor-example"
  interval: 60s  # Check every minute for demo
  log_level: "info"
  enable_metrics: true
  enable_alerts: true
  worker_count: 2

newrelic:
  api_key: "${NEW_RELIC_API_KEY}"
  account_id: "${NEW_RELIC_ACCOUNT_ID}"
  region: "US"

alerts:
  channels:
    - name: "console-alerts"
      type: "log"
      enabled: true
      settings:
        level: "warn"

# Example APIs using public test endpoints
apis:
  # JSONPlaceholder API - always fresh
  - name: "jsonplaceholder-posts"
    url: "https://jsonplaceholder.typicode.com/posts"
    format: "json"
    jq: ".[:5]"  # Take only first 5 posts
    event_type: "ExamplePosts"
    enabled: true
    attributes:
      source: "jsonplaceholder"
      type: "posts"
    staleness:
      enabled: true
      threshold: 10m  # Very lenient for demo
      behavior: "continue"

  # HTTPBin API - for testing various responses
  - name: "httpbin-headers"
    url: "https://httpbin.org/headers"
    format: "json"
    event_type: "ExampleHeaders"
    enabled: true
    attributes:
      source: "httpbin"
      type: "headers"
    staleness:
      enabled: true
      threshold: 5m
      behavior: "alert"

  # Cat Facts API - usually fresh
  - name: "cat-facts"
    url: "https://catfact.ninja/facts?limit=3"
    format: "json"
    jq: ".data"
    event_type: "ExampleCatFacts"
    enabled: true
    attributes:
      source: "catfact.ninja"
      type: "facts"
    staleness:
      enabled: true
      threshold: 30m
      behavior: "skip"

  # Example disabled API
  - name: "disabled-example"
    url: "https://httpbin.org/json"
    format: "json"
    event_type: "DisabledExample"
    enabled: false  # This won't be processed
    staleness:
      enabled: false