global:
  name: "enhanced-flex-monitor"
  interval: 30s
  log_level: "info"
  enable_metrics: true
  enable_alerts: true
  worker_count: 4

newrelic:
  api_key: "${NEW_RELIC_API_KEY}"
  region: "EU"
  account_id: "${NEW_RELIC_ACCOUNT_ID}"

alerts:
  channels:
    - name: "log-alerts"
      type: "log"
      enabled: true

apis:
  - name: "service-metrics"
    url: "https://jsonplaceholder.typicode.com/posts/1"
    fallback_url: "https://httpbin.org/json"
    format: "json"
    jq: ". | {id, title, userId}"
    event_type: "ServiceMetrics"
    enabled: true
    attributes:
      service: "example-api"
      environment: "production"
      team: "platform"
    staleness:
      enabled: true
      threshold: 1us
      behavior: "alert"
      check_url: "https://jsonplaceholder.typicode.com/posts/1"

  - name: "performance-data"
    url: "https://httpbin.org/json"
    fallback_url: "https://jsonplaceholder.typicode.com/comments/1"
    format: "json"
    event_type: "PerformanceData"
    enabled: true
    attributes:
      source: "performance-monitoring"
      format: "json"
    staleness:
      enabled: true
      threshold: 2us
      behavior: "alert"

  - name: "legacy-system"
    url: "https://jsonplaceholder.typicode.com/users/1"
    format: "json"
    event_type: "LegacyData"
    enabled: true
    attributes:
      system: "legacy"
      criticality: "low"
    staleness:
      enabled: true
      threshold: 1us
      behavior: "continue"

  - name: "static-config"
    url: "https://jsonplaceholder.typicode.com/todos/1"
    format: "json"
    event_type: "ConfigData"
    enabled: true
    attributes:
      type: "configuration"
    staleness:
      enabled: false

  - name: "complex-data"
    url: "https://jsonplaceholder.typicode.com/posts"
    fallback_url: "https://httpbin.org/get"
    format: "json"
    jq: '. | map(select(.id <= 5)) | map({id: .id, title: .title, userId: .userId})'
    event_type: "ComplexData"
    enabled: true
    attributes:
      complexity: "high"
      transformation: "jq"
    staleness:
      enabled: true
      threshold: 10s
      behavior: "alert"
      check_url: "https://jsonplaceholder.typicode.com/posts"
